### PR TITLE
mobx ^5 updates

### PR DESCRIPTION
**Pull request by MikeSha**
1) Replace `extendObservable` with `set`
2) Added a method for setting server errors to the field (`fieldState.setServerErrors`)
3) Validate form on submit before request (show errors)

### CODE REVIEW

**Comment by MikeSha** [comment]
Looks like this is the library that almost fits to my project :) Thanks!

**Comment by ansmith** [comment]
Thanks @MikeSha, I'll review this ASAP

**Comment by ansmith** [comment]
Ok this looks good. I'm going to change the mobx peer dependency so you don't get warnings when using 5.x separately.

**Comment by michaeljho** [comment]
Nice! Thanks @MikeSha

**Pull request merged**
